# Generated by Django 2.1.5 on 2019-02-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('user_passwd', models.CharField(max_length=255)),
                ('user_crediential', models.CharField(max_length=128)),
                ('user_token', models.CharField(max_length=64)),
            ],
        ),
    ]
