# Generated by Django 2.1.5 on 2019-02-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_token',
        ),
        migrations.AddField(
            model_name='user',
            name='user_regtime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
