# Generated by Django 4.2.9 on 2024-01-06 06:45

from django.db import migrations, models


def add_default_roles(app, schema):
    from ..models import Role

    datas = [
        dict(name="test-01", props=dict(a="b"), description="aaa")
    ]

    for each in datas:
        Role(**each).save()

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.CharField(max_length=1024)),
                ("props", models.JSONField(verbose_name="角色描述")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(add_default_roles)
    ]
