# Generated by Django 2.1.7 on 2019-02-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0002_auto_20190215_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='p_pic',
            field=models.FileField(upload_to='media/'),
        ),
    ]
